config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  resources :contacts

  root 'contacts#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :phones
  accepts_nested_attributes_for :phones

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phones, length: { is: 3 }

  def name
    [firstname, lastname].join(' ')
  end

  def self.by_letter(letter)
    where("lastname LIKE ?", "#{letter}%").order(:lastname)
  end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact

  validates :phone, uniqueness: { scope: :contact_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate
    redirect_to login_url, alert: 'Please log in first' if current_user.nil?
  end

  def can_administer?
    redirect_to root_url, alert: 'Access denied.' unless administrator?
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def administrator?
    current_user && current_user.admin?
  end

  helper_method :administrator?
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # before_action :authenticate, except: [:index, :show]
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    if params[:letter]
      @contacts = Contact.by_letter(params[:letter])
    else
      @contacts = Contact.order('lastname, firstname')
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    %w(home office mobile).each do |phone|
      @contact.phones.build(phone_type: phone)
    end
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:firstname, :lastname, :email,
        :phones_attributes => [:id, :phone, :phone_type])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Email or password is invalid.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate
  before_action :can_administer?, except: [ :index ]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_url, notice: 'New user created.'
    else
      render :new
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user].delete :admin unless current_user.try(:admin?)
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-inputs'>
    <div class="form-group">
      <%= f.label :firstname %><br>
      <%= f.text_field :firstname %>
    </div>
    <div class="form-group">
      <%= f.label :lastname %><br>
      <%= f.text_field :lastname %>
    </div>
    <div class="form-group">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <%= f.fields_for :phones do |builder| %>
      <div class="form-group">
        <%= builder.hidden_field :phone_type %>
        <%= builder.label :phone, "#{builder.object.phone_type.capitalize} phone" %><br>
        <%= builder.text_field :phone %>
      </div>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<% if not @contacts.empty? %>
  <table class='table table-striped table-hover'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <% if current_user %>
          <th></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= link_to contact.name, contact %></td>
          <td><%= contact.email %></td>
          <% if current_user %>
            <td style='text-align:right;'>
              <%= link_to 'Edit', edit_contact_path(contact), class: 'btn btn-default btn-xs' %>
              <%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    No contacts found.
  </p>
<% end %>

<% if current_user %>
  <div class='form-actions'>
    <%= link_to 'New Contact', new_contact_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>

<p>
  <%= @contact.email %>
</p>

<% unless @contact.phones.empty? %>
  <h2>Phones</h2>

  <ul>
    <% @contact.phones.each do |phone| %>
      <li>
        <%= phone.phone_type %>
        <%= phone.phone %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if current_user %>
  <div class='form-actions'>
    <%= link_to 'Edit', edit_contact_path(@contact), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>BigCo Company Directory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">BigCo, Inc.</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", '#about_us', data: {toggle: 'modal', target: '#about_us' } %></li>
        <li><%= link_to "Contact Us", '#' %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <% if administrator? %>
            <li><%= link_to 'Users', users_path %></li>
          <% end %>
          <li><%= link_to 'Log Out', logout_path %></li>
        <% else %>
          <li><%= link_to 'Log In', new_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="btn-group btn-group-justified">
    <% ('A'..'Z').each do |letter| %>
      <%= link_to letter, contacts_path(letter: letter), class: 'btn btn-default' %>
    <% end %>
    <%= link_to 'All', contacts_path, class: 'btn btn-default' %>
  </div>

  <% flash.each do |name, msg| %>
    <div class='alert alert-<%= name == "notice" ? "success" : "error" %>'>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= msg %>
    </div>
  <% end %>

  <%= yield %>
</div>

<div class="modal fade" id="about_us">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">About BigCo, Inc.</h4>
      </div>
      <div class="modal-body">
        <p>BigCo produces the finest widgets in all the land.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<table class='table table-striped table-hover'>
  <tr>
    <th>Email</th>
    <th>Admin?</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %>
      <td><%= user.admin? %>
    </tr>
  <% end %>
</table>

<% if administrator? %>
  <div class='form-actions'>
    <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class='error_messages'>
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-inputs'>
    <div class='form-group'>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class='form-group' id='password'>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class='form-group' id='password_confirmation'>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class='form-group'>
      <%= f.label :admin do %>
        <%= f.check_box :admin %>
        Administrator?
      <% end %>
    </div>
  </div>

  <div class='form-actions'>
    <%= f.submit 'Create User', class: 'btn btn-primary' %>
  </div>
<% end %>